## Kafka Configuration ##
bootstrap.servers=localhost:9092

# Consumer
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=???
max.poll.records=100000
#earliest: group id? ??? ? ?? ?? ??? offset ?? ???? ???.
#latest: group id? ??? ? ?? ?? ??? offset ?? ???? ???.
auto.commit.enable= latest
fetch.min.bytes=10000
fetch.max.wait.ms=100

# Producer
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
#kafka cluster? ???? ??? ? gzip ?? ??? ???? ???.
compression.type=gzip
#producer? linger.ms ?? ?? ??? ???? ??
linger.ms=50
#producer? batch.size ?? ???? ?? ?? ???? ??
batch.size=163840
acks=1
buffer.memory=1000000

## DB Configuration ##
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/idpp
spring.datasource.username=root
spring.datasource.password=Sirenx123456/

## App Configuration ##
converter.threadCnt=7
converter.org.topic=Org_test2
converter.std.topic=Std_test
converter.error.topic=Error
converter.nomaster.topic=nomaster
converter.plantcodes=VINTAN2
